# project(bits-test)

# add_executable(${PROJECT_NAME}
#   bits-test.cpp
# )

# # Link all standard MLIR dialect and conversion libs.
# get_property(dialect_libs GLOBAL PROPERTY MLIR_DIALECT_LIBS)
# target_link_libraries(${PROJECT_NAME}
#   PRIVATE
#     BitsCodegen
#     MLIRParser
#     MLIRSupport
#     ${dialect_libs}
# )
